apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hot-dog
  name: hot-dog
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hot-dog
  template:
    metadata:
      labels:
        run: hot-dog
    spec:
      containers:
        - name: hot-dog
          image: jyee/hot-dog:0.1.6-uninstrumented
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: SAVE_DOG_LAMBDA
              value: "<YOUR AWS LAMBDA URL>"
